import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import NavBar from './ui/navbar/Navbar';
import { Providers } from './lib/providers';
import Auth from './ui/auth/Auth';
import { headers } from 'next/headers';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const headersList = headers();
const middlewareSet = headersList.get('user');
let user = null;

if (middlewareSet) {
  const decodedUser = Buffer.from(middlewareSet, 'base64').toString('utf-8');
  user = JSON.parse(decodedUser);
}
console.log('middlewareSetUser', user);
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          <NavBar />
          <Auth />
          {children}
        </body>
      </html>
    </Providers>
  );
}
